@startuml SequenciaCadastro
actor Membro
actor Recepcionista
actor Instrutor
participant Sistema
database "Banco de Dados" as DB

'== Chegada do membro ==
Membro -> Recepcionista: Apresenta dados pessoais
activate Membro
activate Recepcionista
Recepcionista -> Sistema: cadastraMembro(dados)
activate Sistema
Sistema -> DB: salvarMembro(dados)
activate DB
Sistema --> Recepcionista: confirmaçãoCadastro
Recepcionista --> Membro: Confirma Cadastro

'== Pagamento ==
Membro -> Recepcionista: realizaPagamento(valor)
Recepcionista -> Sistema: registrarPagamento(valor)
Sistema -> Sistema: verificarPagamento(valor)
alt "Pagamento confirmado"
Sistema -> DB: salvarPagamento(membro, valor)
Sistema --> Recepcionista: Pagamento aceito
Recepcionista --> Membro: Pagamento aceito

'== Cadastro do treino ==
Instrutor -> Sistema: gerarTreino(membro)
activate Instrutor
Sistema -> DB: salvarTreino(membro, treino)
Sistema --> Instrutor: confirmaçãoCadastroTreino
Instrutor -> Membro: apresentaTreino(treino)
Membro --> Instrutor: FinalizaTreino(treino)

'== Registro de atividades ==
Instrutor -> Sistema: registrarAtividade(membro, atividade)
Sistema -> DB: salvarAtividade(membro, atividade)
deactivate DB
Sistema --> Instrutor: Confirma Cadastro Atividade
Instrutor -> Membro: Confirma Atividade
deactivate Instrutor

else "Pagamento recusado"
Sistema --> Recepcionista: Pagamento não aceito
deactivate Sistema
Recepcionista --> Membro: Pagamento não aceito
deactivate Membro
deactivate Recepcionista

end

@enduml
